# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: standards.digital.health.nz
# email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  FHIR Standards for NZ localisation: namespaces, identifiers, and codesets
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://standards.digital.health.nz" # the base hostname & protocol for your site
github_username:  FHIR-NZ

# Build settings
markdown: kramdown
